let articles= [
    {
        "title": "Le lion de Némée",
        "description": "Le lion est fils d'Orthos, le chien de Géryon, et de la Chimère ou d'Échidna, à l'instar du Sphinx de Thèbes. Une tradition minoritaire lui attribue pour père Typhon, sans que la mère ne soit précisée ; une autre encore mentionne Séléné, déesse de la lune, comme sa mère. Élevé par Héra, il fait régner la terreur dans la région de Némée, en Argolide. Il présente la particularité d'avoir une peau impénétrable. \nTuer ce monstre et le ramener à Eurysthée constitue le premier des douze travaux qu'Héraclès doit accomplir. À son arrivée à Cléones, le héros s'arrête dans la hutte d'un laboureur, nommé Molorchos, qui veut lui offrir un sacrifice, comme à un dieu. Refusant pareil honneur, Héraclès lui demande d'attendre un mois. Ce mois écoulé, ou bien il méritera un sacrifice au titre de héros mort, ou bien il aura tué la bête, auquel cas Molorchos pourra alors offrir le sacrifice à Zeus. Un soir, Héraclès surprend le lion sur le versant d'une colline, après le repas de la bête. Dissimulé, il tire sur elle à coup de flèches. Mais il s'aperçoit rapidement que le monstre est invulnérable. Ses flèches, offertes pourtant par Apollon, rebondissent sur son cuir. Le lion charge, Héraclès évite l'assaut. Il combat armé seulement de sa massue en bois d'olivier. Il en frappe le lion, puis l'étouffe, brisant sa massue dans la mêlée.\nUne autre version veut qu'Héraclès parvienne à enfermer le lion dans son antre, et l'étouffe de ses deux mains. Il l'écorche en utilisant les propres griffes du monstre pour entamer la peau coriace. Il nettoie la peau (que ni le feu, ni le fer ne peuvent entamer) et s'en revêt. Zeus met le lion dans le firmament, au nombre des constellations. Molorchos est en train de sacrifier au héros lorsqu'Héraclès arrive à Cléones. À son retour à Tirynthe, le héros lance la peau aux pieds d'Eurysthée, qui en est si terrifié qu'il saute dans une jarre pour s'y cacher. Il ordonne à Héraclès de déposer dorénavant ses trophées à l'extérieur de la ville et de ne communiquer avec lui que par l'intermédiaire de Coprée, son héraut.",
        "imageUrl": "/media/lion.jpg",
        "imageAlt": "illustration du lion de Némée"
    },
    {
        "title": "L'hydre de Lerne",
        "description": "L'Hydre vivait dans une caverne près du lac de Lerne. Héraclès fut envoyé par le roi Eurysthée pour la tuer (c'est le second des « douze travaux » d'Héraclès).\nHésiode donne peu d'information sur la mort de l'Hydre :\n« [...] Hercule ; mais ce fils de Zeus, armé du glaive destructeur et secondé du vaillant Iolaos, immola cette hydre, d'après les conseils de la belliqueuse Athéna. ».\nLe pseudo-Apollodore est plus détaillé :\n« Le second des travaux qu'il lui ordonna, fut de tuer l'Hydre de Lerne . Cette Hydre, nourrie dans les marais de Lerne, sortait dans les champs ; ravageait le pays et détruisait les troupeaux. Elle était d'une grandeur démesurée; elle avait neuf têtes, dont huit étaient mortelles, et la neuvième immortelle. Hercule monté sur son char, qu'Iolaos conduisait, arriva à Lerne, où il arrêta ses chevaux. Ayant trouvé l'Hydre sur une petite élévation, près des sources de la fontaine Amymone où était son repaire, il la força à en sortir en lui lançant des traits enflammés. Il la saisit alors et l'arrêta : mais, s'étant entortillée autour d'un de ses pieds, elle l'entravait lui-même. Il frappait ses têtes à coups de massue, et cela ne servait de rien, car pour une qu'il abattait, il en renaissait deux : de plus, un crabe monstrueux prêtait secours à l'Hydre en le mordant au pied, il commença donc par tuer le crabe; il appela ensuite à son aide Iolaos, qui ayant mis le feu à une partie de la forêt voisine, brûlait avec des tisons enflammés les têtes à mesure qu'elles repoussaient, et les empêchait de renaître. Etant ainsi parvenu à détruire ces têtes renaissantes, il enterra celle qui était immortelle sur le chemin de Lerne à Eléonte, et mit une très grosse pierre dessus. Ayant ensuite ouvert son corps, il trempa la pointe de ses flèches dans son fiel. Eurysthée ne voulut point que cette action fut comptée dans les douze travaux, parce que, pour détruire l'Hydre, il avait eu besoin du secours d'Iolaos. ».\nHéraclès trempa ses flèches dans le sang de la bête afin de rendre mortelle leur blessure. Ce sang entrera dans la composition du philtre empoisonné que le centaure Nessos, en mourant, offrit à Déjanire. Ce poison provoquera la mort d'Héraclès. Ces flèches empoisonnées causeront la mort des centaures Chiron et Nessos, de Géryon. Héraclès les léguera à son compagnon Philoctète et, ce dernier s'étant blessé avec l'une d'elle, il tombera malade et sera rejeté par les Grecs en route vers Troie.\nLe sang de l'Hydre se serait déversé dans les eaux du fleuve Anigros et leur aurait donné une odeur pestilentielle.",
        "imageUrl": "/media/hydre.jpg",
        "imageAlt": "illustration de l'hydre de Lerne"
    },
    {
        "title": "La biche de Cérynie",
        "description": "Aux dires de Callimaque de Cyrène, cinq biches rapides, de la stature d'un taureau, paissaient sur les bords du fleuve thessalien Anauros, au pied du mont Parrhasion. Bien que femelles et donc par nature dépourvues de bois, ces animaux avaient des cornes dorées et des sabots d'airain.\nArtémis les pourchassa, et en captura quatre qu'elle attela à son quadrige. La cinquième s'échappa en traversant le Céladon jusqu'à la colline de Cérynie. Le cervidé étant de ce fait consacré à Artémis, il était défendu de la toucher et a fortiori de la tuer.\nSuivant le désir d'Eurysthée, Héraclès poursuivit l'animal toute une année, sans l'atteindre à travers la Grèce, la Thrace et l'Istrie. La biche finit cependant par s'épuiser, et se réfugia sur le mont Artémision. Elle voulut traverser le Ladon, quand Héraclès lui décocha une flèche entre l'os et le tendon de la patte, l'immobilisant sans qu'une goutte de sang ne fut versée. Il chargea l'animal sur ses épaules et traversa l'Arcadie pour se rendre chez Eurysthée. En chemin, il rencontra Artémis et Apollon, qui l'accusèrent de sacrilège pour avoir maltraité la bête. Le chasseur s'en récusa et fit ressortir l'obligation dans laquelle il se trouvait, rejetant la responsabilité sur Eurysthée. La colère d'Artémis s'apaisa et elle l'autorisa à se rendre à Mycènes à condition de relâcher ensuite sa protégée sans lui faire de mal.\nD'après Pindare, la biche n'est autre que la Pléiade Taygète, qu'Artémis métamorphosa pour la soustraire aux avances de Zeus. L'auteur raconte que Héraclès poursuivit l'animal à travers l'Istrie, dans le pays des Hyperboréens et jusque chez les Bienheureux. La poursuite l'entraîna donc au-delà de l'Arcadie et au terme de cette chasse, il aurait trouvé l'olivier sauvage qui servira de couronne au vainqueur des Jeux olympiques.\nLa version contradictoire et isolée d'Euripide raconte que la biche, de taille gigantesque, vivait dans les bois d'Œnoé, en Argolide et ravageait les récoltes. Héraclès la tua et consacra les bois de l'animal dans le temple d'Artémis Œnoatis afin de se réconcilier avec la déesse.",
        "imageUrl": "/media/biche.jpg",
        "imageAlt": "illustration de la biche de Cérynie"
    },
    {
        "title": "Le sanglier d'Érymanthe",
        "description": "Pendant son voyage vers l'Arcadie, Héraclès demande l'hospitalité à un centaure, Pholos. Ce dernier accepte de bon cœur et est très serviable : bien qu'il mange la viande crue, il la sert cuite à Héraclès. Au fur et à mesure du repas, le héros sent venir la soif. C'est alors qu'il aperçoit un grand tonneau de vin. Il demande à Pholos de lui en servir, mais celui-ci refuse car c'est un bien commun des centaures. Héraclès insiste fortement et finit par le convaincre. Le maître de maison et le demi-dieu commencent donc à s'en abreuver. Venant de finir leur dégustation, ils aperçoivent au loin une horde de centaures armés de lances et de gourdins qui avaient senti l'odeur du vin. Héraclès leur tire dessus à l'aide de flèches empoisonnées, parvenant à les éliminer. Mais alors qu'il donne leur sépulture aux centaures morts, Pholos se blesse avec l'une des flèches d'Héraclès, empoisonnée par le sang de l'hydre de Lerne ; et Chiron, un autre centaure qui n'avait pas participé à la bataille, est blessé par erreur à un genou, qui lui provoque des douleurs sans fin : ne pouvant mourir, il demande aux dieux de lui retirer son immortalité afin de cesser de souffrir. C'est ainsi que meurent les deux seuls centaures bons et sages de la mythologie grecque.\nArrivant en Arcadie, Héraclès reprend son quatrième travail et se met à pourchasser durant l'hiver la bête gigantesque parcourant l'Érymanthe. Il la cherche durant plusieurs jours, abattant des arbres pour l'apercevoir, et finit par trouver un moyen pour faire sortir le sanglier de sa tanière : il pousse de grands cris. Cela fait, il le course durant plusieurs jours à travers toute la montagne couverte de neige, si bien qu'il arrive au sommet. Le demi-dieu suit le monstre à la trace et lui jette constamment des pierres. Ainsi harcelé et épuisé, le sanglier tombe dans un trou creusé et rempli de neige par Héraclès pour le piéger. Comme la bête était paralysée sous le choc, Héraclès le maîtrisa à mains nues et l'enchaîna.\nIl retourne ensuite à Mycènes, le dos chargé de sa proie. Certains racontent qu'Eurysthée, terrifié par la bête, plongea dans sa jarre de bronze à la vue de la bête vivante. Héraclès déposa la bête sur la place du marché où le sanglier fut tué par un boucher resté anonyme : ses formidables défenses ont été conservées à Cumes, dans le temple d'Apollon.",
        "imageUrl": "/media/sanglier.jpg",
        "imageAlt": "illustration du sanglier d'Érymanthe"
    },
    {
        "title": "Les écuries d'Augias",
        "description": "Le nettoyage des écuries d'Augias est le cinquième (ou le sixième, selon les auteurs) des douze travaux d'Héraclès.\nAugias possédait 3 000 bœufs, mais les écuries de ses animaux étaient tellement sales qu'on ne pouvait plus y entrer; elles n'avaient plus été nettoyées depuis trente ans.\nLa tâche d'Héraclès fut de nettoyer ces écuries, ce qu'il fit en une journée, en détournant les eaux des fleuves Alphée et Pénée pour les décrasser en profondeur. Quand il estima que ces dernières étaient propres, il détruisit les dérivations qu'il avait construites. Le soleil couchant vint sécher les écuries et celles-ci redevinrent enfin propres et saines.\nCe travail ne fut cependant pas comptabilisé ; Eurysthée prétexta qu'Héraclès avait demandé à Augias d'être payé pour la tâche. Augias ne versa jamais ce paiement (il lui avait promis 300 bœufs) et chassa Héraclès quand il vint le lui réclamer. Irrité, Héraclès leva une armée, prit la ville d'Élis, et tua Augias ainsi que tous ses fils sauf un, Phylée, qui avait pris le parti d'Héraclès. En récompense, le héros le plaça sur le trône d'Élide, le faisant ainsi succéder à son père.\nCe travail et la mauvaise foi d'Augias sont citées par Pindare dans les Olympiques vers 26 :\n« Docile aux lois de Jupiter, je veux aussi chanter ces antiques jeux que le vaillant Hercule institua près du tombeau de Pélops, après avoir immolé à sa vengeance les deux fils de Neptune, le brave Ctéatus (184) et son frère Eurytus. Il voulait forcer Augias à lui payer le salaire promis à ses travaux, et ce roi parjure le lui refusait. »",
        "imageUrl": "/media/ecuries.jpg",
        "imageAlt": "illustration d'un cheval de l'écuries d'Augias"
    },
    {
        "title": "Les oiseaux du lac Stymphale", "description": "Des oiseaux infestaient les bois près du lac Stymphale, en Arcadie. Ils tuaient leurs proies grâce à leurs plumes d'acier, piquantes et tranchantes, qu'ils utilisaient comme des flèches. D'autres légendes racontent qu'ils étaient simplement munis de griffes et d'un bec d'airain.\nHéraclès les effraya au moyen de crotales de bronze qu'Athéna lui avait offert, en tua un certain nombre, puis chassa le reste. Une autre légende raconte qu'Héraclès commença par les tuer à l'aide de ses flèches, mais ils étaient tellement nombreux et se reproduisaient si vite, qu'à la fin de la journée Héraclès n'avait plus de flèches et que les oiseaux étaient plus nombreux que dans la matinée. Héraclès, dans un mouvement de rage, frappa alors son épée contre son bouclier, ce qui fit fuir les oiseaux. Il continua jusqu'à ce que tous les oiseaux tombent d'épuisement dans le lac et se noient.",
        "imageUrl": "/media/oiseaux.jpg",
        "imageAlt": "illustration des oiseaux du lac Stymphale"
    },
    {
        "title": "Le taureau crétois de Minos",
        "description": "Ce taureau crétois est assimilé, selon les auteurs soit au taureau blanc offert par Poséidon à Minos pour être sacrifié, mais qui fut épargné par Minos et dont Pasiphaé tomba amoureuse (elle conçut de lui le Minotaure);\nsoit à celui dont Zeus prit la forme pour enlever Europe et l'amener en Crète.\nDans la première version, Poséidon se vengea en rendant le taureau furieux et en lui faisant dévaster les terres de Crète. Héraclès reçut pour tâche de le capturer vif (le septième de ses douze travaux) : il y parvint en sautant sur lui et en lui saisissant les cornes. Il revint en Grèce sur le dos de l'animal à travers la mer qui sépare la Crète de Tyrinthe en Argolide, dont le roi est Eurysthée. Celui-ci, ayant vu l'animal, le relâcha : le taureau erra un temps à travers la Grèce et s'installa finalement près de Marathon. Là, il se rendit coupable de plusieurs méfaits, avant d'être terrassé par Thésée. Selon Plutarque, Thésée maîtrise le taureau et l'exhibe à Athènes, puis le sacrifie à Apollon Delphinien.",
        "imageUrl": "/media/taureau.jpg",
        "imageAlt": "illustration du taureau crétois de Minos"
    },
    {
        "title": "les cavales de Diomède",
        "description": "Pour son huitième travail, Héraclès reçoit l'ordre de les dérober et de les ramener à Argos. Il assomme donc le roi et jette son corps moribond aux cavales, avant de regagner Argos avec elles.\nSelon une autre version de la légende, Héraclès amène avec lui plusieurs jeunes gens pour l'aider, dont Abdère, son compagnon. Abdère est tué par l'une des juments et c'est pour le venger qu'Héraclès jette Diomède à ses propres juments. Héraclès enterre ensuite Abdère et fonde autour du tombeau la ville d'Abdère. Une fois leur maître dévoré, les animaux deviennent dociles et Héraclès les mène au roi Eurysthée, à Argos.\nUne troisième version indique qu'Héraclès piège les juments sur une île, tue Diomède et le donne à manger à ses juments qu'il musèle ensuite pour les mener à Eurysthée.\nSelon la tradition grecque, Bucéphale, cheval d'Alexandre le Grand, descendait de l'une des juments de Diomède. Les juments se nommaient Dinos, Lampon, Podargos et Xanthos.",
        "imageUrl": "/media/horses.jpg",
        "imageAlt": "illustration des cavales de Diomède"
    },
    {
        "title": "la ceinture d'Hippolyte",
        "description": "Elle est surtout célèbre pour sa ceinture, objet du neuvième des douze travaux d'Héraclès. Il s'agissait pour lui de s'emparer de la ceinture d'Hippolyte qui lui fut donnée par son père, et que convoitait la fille d'Eurysthée. Alors qu'il allait s'en emparer, la déesse Héra sema la panique et le héros tua Hippolyte. Selon une autre version, c'est la sœur d'Hippolyte qui est tuée, tandis que la reine est par la suite elle-même enlevée par Thésée. Selon une autre version encore, c'est Penthésilée qui la tue et devient reine à sa place. Certains auteurs font de Oeolyce la propriétaire de la ceinture.\nChez certains auteurs, Héraclès fit prisonnier Mélanippe, l'auxiliaire d'Hippolyte, qui lui remit la ceinture comme prix de sa liberté. La ceinture, dans un tel cadre, représente un objet recherché pour sa valeur symbolique au sein d'une tribu. Les populations de la fin du Néolithique ont en effet porté cette pièce vestimentaire qu'on a retrouvée dans nombre de sépultures des premiers âges des métaux un peu partout en Europe, composée d'un disque de métal plus ou moins précieux sur le devant, et plus ou moins ouvragé selon la classe sociale de ceux ou celles qui la portaient ; autrement dit un peu comme les hidalgos espagnols, qui après la découverte des Amériques, portaient en sautoir leur colliers d'anneaux d'or composant leur fortune.",
        "imageUrl": "/media/belt.jpg",
        "imageAlt": "illustration de la ceinture d'Hippolyte"
    },
    {
        "title": "La pommes d'or du jardin des Hespérides",
        "description": "Le onzième des Travaux d'Héraclès consistait à rapporter les fruits d'or d'un pommier, cadeau de Zeus à Héra. Elle l'avait planté dans son jardin divin qui se trouvait sur les pentes du mont Atlas, là où les chevaux du char du Soleil achèvent leur randonnée en se couchant à l'ouest de l'océan Atlantique. Un jour, Héra s'aperçut que les filles d'Atlas, les Hespérides, à qui elle avait confié la garde de l'arbre, volaient les pommes ; elle plaça alors un dragon à cent têtes, Ladon, autour du pommier pour en interdire l'accès. Après maintes péripéties, Héraclès obtint de Nérée quelques renseignements, notamment que les pommes d'or poussent dans un jardin situé dans « l'Extrême Occident » où vivent les nymphes Hespérides. Mais ces informations un peu vagues laissent Héraclès dans le flou, et Nérée profite de ce moment d'inattention pour se transformer en serpent et se faufiler entre deux pierres. Héraclès se dirige déjà vers les terres de l'ouest qu'il a eu l'occasion de visiter lors de son périple dans le royaume de Géryon. Après quelques jours de voyage il atteint la région de Tartessos près de Gadès en Hispanie.\nHéraclès franchit le détroit de Gibraltar d'où s'élèvent les colonnes à son nom, afin de rencontrer le Titan Atlas, car ce dernier est le seul à pouvoir l'aider dans sa quête des pommes d'or poussant dans ce fabuleux jardin des Hespérides, situé dans cette région extra-océanique réservée uniquement aux immortels. Arrivé sur la pointe nord du continent africain, Héraclès découvre l'immense Atlas courbé sous le poids de la voûte céleste qu'il est chargé de supporter, depuis la défaite des Titans contre les dieux de l'Olympe. Atlas écoute les raisons de sa visite et lui propose de se rendre au jardin des Hespérides pour y cueillir trois pommes d'or, mais à la seule condition qu'Héraclès porte le fardeau de la voûte céleste. Ce dernier accepte et endosse sur ses épaules le poids du ciel tandis qu'Atlas part chercher les fruits d'or. Après plusieurs heures d'attente, Atlas réapparaît avec trois fruits d'or à la main. Il se propose d'aller porter lui-même les pommes à Eurysthée. Conscient du risque qui pèse sur lui, Héraclès utilise une ruse : il feint d'accepter le service du Titan et le prie de reprendre le poids du ciel, pour quelques instants seulement, le temps de trouver un bon coussin pour ses épaules. Atlas pose les pommes d'or sur le sol et reprend la voûte céleste en toute confiance ; mais quand il voit Héraclès ramasser les fruits qu'il a cueillis et s'éloigner avec un geste d'adieu, il réalise qu'il a été dupé.",
        "imageUrl": "/media/apple-trees.jpg",
        "imageAlt": "illustration du verger du jardin des Hespérides"
    },
    {
        "title": "Le géant aux trois corps Géryon",
        "description": "Le texte le plus complet est celui contenu dans la Bibliothèque du pseudo-Apollodore du ier ou iie siècle après J.-C. Dans cette version de l'histoire, Géryon est tué par Héraclès qui peut ainsi s'emparer de son troupeau de bœufs et accomplir le dixième de ses travaux. Héraclès traverse le désert libyen et arrive en Érythie. Alors qu'il vient d'arriver, il tue le bouvier Eurytion, et est attaqué par Orthros, le chien à deux têtes de Géryon. Orthros serait le frère de Cerbère. D'un seul coup de sa massue en bois d'olivier, Héraclès tue le chien. Lorsque Géryon est mis au courant, il s'arme de ses trois boucliers, trois lances et met ses trois casques. Il poursuit Héraclès et tombe, victime d'une flèche empoisonnée qui avait été plongée dans le venin de l'Hydre de Lerne. Héraclès peut ainsi dérober les bœufs et les ramener à Eurysthée.",
        "imageUrl": "/media/boeufs.jpg",
        "imageAlt": "illustration du troupeau de bœufs du géant aux trois corps Géryon"
    },
    {
        "title": "Cerbère",
        "description": "Comme ultime épreuve, Eurysthée demanda à Héraclès de descendre aux Enfers et d'en ramener Cerbère, le chien de garde des portes souterraines.\nHermès et Athéna l'escortèrent jusqu'au séjour des Morts. Il atteignit le Styx et, traversant de grands fleuves de flammes, il parvint aux pieds du trône d'Hadès. Il dut se battre au corps à corps avec lui, mais Héraclès étant plus fort il put le vaincre. Hadès,vaincu lui permit d'emmener Cerbère à la lumière du jour s'il pouvait se rendre maître de l'animal sans le secours d'aucune arme.\nCerbère était un chien monstrueux qui possédait trois têtes et dont le corps se terminait par une queue de dragon. Sa sonore voix d'airain terrorisait tous ceux qui l'approchaient. Sans arme, revêtu seulement de la peau du lion de Némée, Héraclès se présenta devant Cerbère. Il le saisit par le cou, juste à l'endroit où se réunissaient les trois têtes et, quoique mordu, le serra si fort que le chien, sentant la mort venir, se décida à suivre le héros. Héraclès enchaîna l'animal et le tirant hors de la caverne d'Acherusia, vint le montrer à Eurysthée. Terrifié, celui-ci comme à son habitude, se cacha dans une jarre puis ordonna aussitôt de renvoyer le monstre aux Enfers.\"",
        "imageUrl": "/media/Cerberus.jpg",
        "imageAlt": "illustration du chien des enfers Cerbère"
    }
];

let works= [
    "Étouffer le lion de Némée à la peau impénétrable, et rapporter sa dépouille.",
    "Tuer l'hydre de Lerne, dont les têtes tranchées repoussaient sans cesse.",
    "Capturer la biche de Cérynie aux sabots d'airain et aux bois d'or, créature sacrée d'Artémis.",
    "Ramener vivant l'énorme sanglier d'Érymanthe.",
    "Nettoyer les écuries d'Augias, qui ne l'avaient jamais été, car elles étaient si grandes que personne n'avait jamais eu le courage de le faire.",
    "Tuer les oiseaux du lac Stymphale aux plumes d'airain.",
    "Dompter le taureau crétois de Minos, que celui-ci n'avait pas voulu sacrifier à Poséidon.",
    "Capturer les cavales de Diomède (juments mangeuses d'hommes).",
    "Rapporter la ceinture d'Hippolyte, fille d'Arès et reine des Amazones.",
    "Rapporter les pommes d'or du jardin des Hespérides, que gardait Ladon.",
    "Vaincre le géant aux trois corps Géryon, et voler son troupeau de bœufs.",
    "Descendre aux Enfers et enchaîner Cerbère, le chien aux trois têtes puis le présenter à Eurysthée pour témoigner de son succès."
];
